# Generated by Django 4.1.3 on 2023-01-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=15)),
                ('pol', models.CharField(choices=[('M', 'M'), ('W', 'W')], max_length=1)),
                ('vozrast', models.DateTimeField()),
                ('pochta', models.EmailField(max_length=255)),
            ],
        ),
    ]
